# ==========================================
# NSPIRE Scoring Engine
# ==========================================

#' Apply Internal Pre-Inspection Audit
#'
#' Simulates the property management team walking the units before the official inspection.
#' Items caught during this audit are flagged as found. In a full pipeline, these are the 
#' items that get sent to the `schedule_repairs` function to be fixed beforehand.
#'
#' @param defects_df A \code{data.frame} generated by \code{run_simulation}.
#' @param audit_catch_rate Numeric. Probability (0 to 1) that the internal team catches a defect.
#' @param seed Integer. Optional random seed.
#' @return A \code{data.frame} with an added \code{caught_in_audit} boolean column.
#' @importFrom stats runif
#' @export
apply_audit_fixes <- function(defects_df, audit_catch_rate, seed = NULL) {
  if (!is.null(seed)) set.seed(seed)
  
  if (nrow(defects_df) == 0) {
    defects_df$caught_in_audit <- logical(0)
    return(defects_df)
  }
  
  # Roll probability for the internal team catching the defect
  defects_df$caught_in_audit <- stats::runif(nrow(defects_df)) <= audit_catch_rate
  
  return(defects_df)
}

#' Calculate Official Inspection Score
#'
#' Calculates the final building score based on un-audited defects that the official 
#' inspector successfully identifies.
#'
#' @param defects_df A \code{data.frame} that has been processed by \code{apply_audit_fixes}.
#' @param scoring_csv Path to the scoring rubric configuration CSV.
#' @param rubric Character. The name of the rubric to use (e.g., "NSPIRE", "UPCS").
#' @param starting_score Numeric. The maximum possible score (default 100).
#' @param total_units_inspected Integer. If provided, normalizes the deductions by sample size (HUD standard).
#' @return A \code{list} containing the final score, total deductions, points lost, and an itemized deduction table.
#' @export
calculate_inspection_score <- function(defects_df, scoring_csv, rubric = "NSPIRE", starting_score = 100, total_units_inspected = NULL) {
  # Load scoring matrix
  scoring_df <- read.csv(scoring_csv, stringsAsFactors = FALSE, strip.white = TRUE)
  
  # Filter for chosen rubric
  rubric_df <- scoring_df[scoring_df$rubric_name == rubric, ]
  if (nrow(rubric_df) == 0) {
    stop("CRITICAL ERROR: Rubric '", rubric, "' not found in scoring config.")
  }
  
  if (nrow(defects_df) == 0) {
    return(list(final_score = starting_score, total_deductions = 0, points_lost = 0, itemized = data.frame()))
  }
  
  # Check if the audit was run. If not, assume no internal audit happened!
  if (!"caught_in_audit" %in% colnames(defects_df)) {
    defects_df$caught_in_audit <- FALSE
  }
  
  # CRITICAL LOGIC: An item hits the official score ONLY IF:
  # 1. The internal team MISSED it during their audit (caught_in_audit == FALSE)
  # 2. AND the official inspector actually CAUGHT it (is_caught == TRUE)
  score_hits <- defects_df[!defects_df$caught_in_audit & defects_df$is_caught, ]
  
  if (nrow(score_hits) == 0) {
    return(list(final_score = starting_score, total_deductions = 0, points_lost = 0, itemized = data.frame()))
  }
  
  # Merge with deduction values based on severity
  itemized <- merge(score_hits, rubric_df[, c("severity", "deduction")], by = "severity", all.x = TRUE)
  
  # If any severity wasn't found in the rubric, default to 0 to prevent NA math errors
  itemized$deduction[is.na(itemized$deduction)] <- 0
  
  total_deductions <- sum(itemized$deduction)
  
  # NSPIRE/UPCS divides total point deductions by the number of units inspected
  if (!is.null(total_units_inspected) && total_units_inspected > 0) {
    points_lost <- total_deductions / total_units_inspected
  } else {
    points_lost <- total_deductions
  }
  
  # Score cannot drop below 0
  final_score <- max(0, starting_score - points_lost) 
  
  return(list(
    final_score = final_score,
    total_deductions = total_deductions,
    points_lost = points_lost,
    itemized = itemized
  ))
}